63530 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
63530 + 0 mapped (100.00%:N/A)
63530 + 0 paired in sequencing
31765 + 0 read1
31765 + 0 read2
63530 + 0 properly paired (100.00%:N/A)
63530 + 0 with itself and mate mapped
0 + 0 singletons (0.00%:N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)
