964177 + 0 in total (QC-passed reads + QC-failed reads)
273011 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
444063 + 0 mapped (46.06%:-nan%)
691166 + 0 paired in sequencing
345583 + 0 read1
345583 + 0 read2
142664 + 0 properly paired (20.64%:-nan%)
160458 + 0 with itself and mate mapped
10594 + 0 singletons (1.53%:-nan%)
20 + 0 with mate mapped to a different chr
15 + 0 with mate mapped to a different chr (mapQ>=5)
