691166 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
170843 + 0 mapped (24.72%:-nan%)
691166 + 0 paired in sequencing
345583 + 0 read1
345583 + 0 read2
141784 + 0 properly paired (20.51%:-nan%)
160158 + 0 with itself and mate mapped
10685 + 0 singletons (1.55%:-nan%)
20 + 0 with mate mapped to a different chr
15 + 0 with mate mapped to a different chr (mapQ>=5)
